# Generated by Django 5.0.1 on 2024-04-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_guests_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='room.room'),
        ),
    ]
