from django.urls import path
from . import views
urlpatterns = [
    path('', views.create_room, name='list_room'),
    path('search_room/', views.search_roomsNumber, name='search_room'),
    path('<int:id>/editroom/', views.edit_room, name='edit_room'),
    path('<int:id>/deleteroom/', views.delete_room, name='delete_room'),
    path('calculate_bill/<int:room_id>/', views.calculate_bill, name='calculate_bill'),
    path('guest/', views.create_guests, name='list_guests'),
    path('guest/search_guest/', views.search_guest, name='search_guests'),
    path('<int:id>/guests_in_room/', views.guests_in_room, name='guests_in_room'),
    path('guest/edit_guest/<int:guest_id>/', views.edit_guest, name='edit_guest'),
    path('guest/delete_guest/<int:guest_id>/', views.delete_guest, name='delete_guest'),
    path('guest/<int:room_id>/guest_checkout/', views.get_guest, name='guest_checkout'),
    path('house/', views.create_house, name='list_house'),
    path('house/search_house/', views.search_nameHouse, name='search_house'),
    path('house/<int:id>/get_rooms/', views.get_rooms, name='get_rooms'),
    path('house/<int:id>/edit_house/', views.edit_house, name='edit_house'),
    path('house/<int:id>/delete_house/', views.delete_house, name='delete_house'),
    path('electricity/', views.create_electricity, name='list_electricity'),
    path('electricity/<int:id>/edit_electricity/', views.edit_electricity, name='edit_electricity'),
    path('electricity/<int:id>/delete_electricity/', views.delete_electricity, name='delete_electricity'),
    path('personnel/', views.create_personnel, name='list_personnel'),
    path('personnel/search_personnel/', views.search_personnel, name='search_personnel'),
    path('personnel/<str:id_personnel>/get_houses/', views.get_house_of_personnel, name='get_house_of_personnel'),
    path('personnel/<str:id_personnel>/edit_personnel/', views.edit_personnel, name='edit_personnel'),
    path('personnel/<str:id_personnel>/delete_personnel/', views.delete_personnel, name='delete_personnel'),
    path('area/', views.create_area, name='list_area'),
    path('area/search_area/', views.search_area, name='search_area'),
    path('area/<int:id>/get_house', views.get_house_of_area, name='get_house_of_area'),
    path('area/<int:id>/edit_area/', views.edit_area, name='edit_area'),
    path('area/<int:id>/delete_area/', views.delete_area, name='delete_area'),
    path('list_statistical/', views.statistical, name='list_statistical'),
    path('information_statiscal_guest/', views.statistical_guest, name='information_statistical_guest'),
    path('information_statiscal_electricity/', views.statistical_electricity, name='information_statistical_electricity'),
    ]

